// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID                    string         `json:"id"`
	Title                 string         `json:"title"`
	RelationID            *string        `json:"relationId,omitempty"`
	RelationName          *string        `json:"relationName,omitempty"`
	Description           *string        `json:"description,omitempty"`
	Content               *string        `json:"content,omitempty"`
	EstablishmentID       *string        `json:"establishmentId,omitempty"`
	Establishment         *Establishment `json:"establishment,omitempty"`
	PublicEstablishmentID *string        `json:"publicEstablishmentId,omitempty"`
	PublishedAt           *string        `json:"publishedAt,omitempty"`
	UserID                *string        `json:"userId,omitempty"`
	User                  *User          `json:"user,omitempty"`
	Likes                 *int           `json:"likes,omitempty"`
	Attachments           *string        `json:"attachments,omitempty"`
	AllowComments         *bool          `json:"allowComments,omitempty"`
	Comments              []*Comment     `json:"comments,omitempty"`
	ShowAuthor            *bool          `json:"showAuthor,omitempty"`
	ShowDate              *bool          `json:"showDate,omitempty"`
	ShowLikes             *bool          `json:"showLikes,omitempty"`
	Thumbnail             *string        `json:"thumbnail,omitempty"`
	CreatedAt             string         `json:"createdAt"`
	UpdatedAt             string         `json:"updatedAt"`
	DeletedAt             *string        `json:"deletedAt,omitempty"`
	CommentKey            *string        `json:"commentKey,omitempty"`
	CategoryIds           *string        `json:"categoryIds,omitempty"`
	Categories            []*Category    `json:"categories,omitempty"`
}

type Category struct {
	ID              string   `json:"id"`
	Title           string   `json:"title"`
	UserID          *string  `json:"userId,omitempty"`
	User            *User    `json:"user,omitempty"`
	Comment         string   `json:"comment"`
	ParentCommentID *int     `json:"parentCommentId,omitempty"`
	ParentComment   *Comment `json:"parentComment,omitempty"`
	Likes           *int     `json:"likes,omitempty"`
	CreatedAt       string   `json:"createdAt"`
}

type Comment struct {
	ID              string   `json:"id"`
	Title           string   `json:"title"`
	UserID          *string  `json:"userId,omitempty"`
	User            *User    `json:"user,omitempty"`
	Comment         string   `json:"comment"`
	ParentCommentID *int     `json:"parentCommentId,omitempty"`
	ParentComment   *Comment `json:"parentComment,omitempty"`
	Likes           *int     `json:"likes,omitempty"`
	CreatedAt       string   `json:"createdAt"`
}

type Establishment struct {
	ID        string     `json:"id"`
	PublicID  string     `json:"publicId"`
	Name      string     `json:"name"`
	UserID    string     `json:"userId"`
	Type      string     `json:"type"`
	Thumbnail *string    `json:"thumbnail,omitempty"`
	DbID      string     `json:"dbId"`
	Latitude  *float64   `json:"latitude,omitempty"`
	Longitude *float64   `json:"longitude,omitempty"`
	Events    []*Event   `json:"events,omitempty"`
	Articles  []*Article `json:"articles,omitempty"`
}

type Event struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Date  string `json:"date"`
}

type Query struct {
}

type User struct {
	ID        string  `json:"id"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     *string `json:"email,omitempty"`
}

type Video struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Date  string `json:"date"`
}
